"""v3 voice engine: Chatterbox (Resemble AI, MIT) on the RTX 4090.

Higher-quality, more natural/expressive narration than Kokoro. Each character is
a zero-shot clone of a license-clean reference clip (generated by Kokoro, Apache-2.0,
in tools/voices_ref/) so timbres are persona-matched (e.g. a YOUNGER male for Vega)
while Chatterbox supplies natural prosody + an `exaggeration` emotion knob.

Drop-in for tts2: exposes synth_line(speaker, text, out_wav) -> float and reuses
the shared pronunciation preprocessor + a light ffmpeg mastering chain. Runs in
the .venv_tts environment (chatterbox-tts + torch cu124).
"""
from __future__ import annotations
import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from tts import preprocess  # shared acronym/ID pronunciation pre-processor

import warnings
warnings.filterwarnings("ignore")

ROOT = Path(__file__).resolve().parent.parent
SR = 24000
REFDIR = ROOT / "tools" / "voices_ref"
CACHE = ROOT / "tools" / "_tmp" / "voicecache_cbx"
CACHE.mkdir(parents=True, exist_ok=True)

# character -> Chatterbox generation knobs (reference clip is voices_ref/<SPEAKER>.wav)
CAST = {
    "NARRATOR":  {"exaggeration": 0.52, "cfg_weight": 0.50, "temperature": 0.78},
    "VEGA":      {"exaggeration": 0.62, "cfg_weight": 0.46, "temperature": 0.80},
    "NOVA":      {"exaggeration": 0.70, "cfg_weight": 0.42, "temperature": 0.85},
    "ARCHIVIST": {"exaggeration": 0.38, "cfg_weight": 0.58, "temperature": 0.72},
    "NULL":      {"exaggeration": 0.82, "cfg_weight": 0.28, "temperature": 0.70},
    "HERALD":    {"exaggeration": 0.58, "cfg_weight": 0.46, "temperature": 0.80},
}

# Light, character-specific mastering (Chatterbox is already natural; just place it
# in the same -16 LUFS soundstage as music/SFX and give each voice a little space).
_NORM = "loudnorm=I=-16:TP=-1.5:LRA=11"
EFFECTS = {
    "NARRATOR":  f"highpass=f=75,acompressor=threshold=-18dB:ratio=2:attack=12:release=120,aecho=0.85:0.9:28:0.12,{_NORM}",
    "VEGA":      f"highpass=f=80,firequalizer=gain_entry='entry(3000,1.5);entry(8000,-2)',acompressor=threshold=-18dB:ratio=2:attack=12:release=120,aecho=0.85:0.9:40:0.16,{_NORM}",
    "NOVA":      f"highpass=f=95,firequalizer=gain_entry='entry(300,-1.5);entry(3500,1.5);entry(9000,-3)',acompressor=threshold=-18dB:ratio=2:attack=10:release=110,aecho=0.85:0.88:22:0.12,{_NORM}",
    "ARCHIVIST": f"highpass=f=105,firequalizer=gain_entry='entry(320,-1);entry(3200,1.5);entry(9000,-2.5)',acompressor=threshold=-18dB:ratio=2:attack=14:release=140,aecho=0.82:0.86:16:0.10,{_NORM}",
    "NULL":      f"rubberband=pitch=0.84,asubboost,highpass=f=50,firequalizer=gain_entry='entry(120,2);entry(400,-1);entry(1500,1);entry(4200,-2.5)',acompressor=threshold=-20dB:ratio=3:attack=8:release=160,aecho=0.8:0.85:95:0.34,lowpass=f=4600,{_NORM}",
    "HERALD":    f"highpass=f=82,firequalizer=gain_entry='entry(3000,1.5);entry(8000,-2)',acompressor=threshold=-18dB:ratio=2:attack=12:release=120,aecho=0.85:0.9:52:0.20,{_NORM}",
}

_MODEL = None
_CONDS: dict = {}


def _model():
    global _MODEL
    if _MODEL is None:
        import torch  # noqa: F401
        from chatterbox.tts import ChatterboxTTS
        dev = "cuda" if __import__("torch").cuda.is_available() else "cpu"
        _MODEL = ChatterboxTTS.from_pretrained(device=dev)
    return _MODEL


def _ref_for(speaker):
    p = REFDIR / f"{speaker}.wav"
    return p if p.exists() else (REFDIR / "NARRATOR.wav")


def _settings(speaker):
    return CAST.get(speaker, CAST["NARRATOR"])


def _synth_raw(speaker, text, raw_path):
    m = _model()
    ref = str(_ref_for(speaker))
    s = _settings(speaker)
    if speaker not in _CONDS:
        m.prepare_conditionals(ref, exaggeration=s["exaggeration"])
        _CONDS[speaker] = m.conds
    m.conds = _CONDS[speaker]
    wav = m.generate(preprocess(text), exaggeration=s["exaggeration"],
                     cfg_weight=s["cfg_weight"], temperature=s["temperature"],
                     repetition_penalty=1.2, min_p=0.05, top_p=1.0)
    import torchaudio as ta
    ta.save(str(raw_path), wav.detach().cpu(), m.sr)


def _key(speaker, text):
    ref = _ref_for(speaker)
    sig = f"cbx|{speaker}|{_settings(speaker)}|{EFFECTS.get(speaker)}|{int(ref.stat().st_mtime)}|{preprocess(text)}"
    return hashlib.md5(sig.encode("utf-8")).hexdigest()


def synth_line(speaker, text, out_wav) -> float:
    out_wav = Path(out_wav)
    out_wav.parent.mkdir(parents=True, exist_ok=True)
    cached = CACHE / f"{_key(speaker, text)}.wav"
    if cached.exists():
        shutil.copyfile(cached, out_wav)
    else:
        raw = out_wav.with_suffix(".raw.wav")
        _synth_raw(speaker, text, raw)
        af = EFFECTS.get(speaker, EFFECTS["NARRATOR"])
        subprocess.run(["ffmpeg", "-y", "-i", str(raw), "-ar", str(SR), "-ac", "1",
                        "-af", af, str(out_wav)],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
        raw.unlink(missing_ok=True)
        shutil.copyfile(out_wav, cached)
    dur = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration",
                          "-of", "csv=p=0", str(out_wav)], capture_output=True, text=True).stdout.strip()
    return float(dur)


if __name__ == "__main__":
    tmp = ROOT / "tools" / "_tmp" / "v3voices"
    lines = [
        ("NARRATOR", "Every modern organization runs on information. Protect it, and you thrive."),
        ("VEGA", "I'm Vega. Twenty guardians defend this citadel. First, AC-6, Least Privilege."),
        ("NOVA", "So that's giving people only the access they actually need? Nothing more?"),
        ("ARCHIVIST", "Employ the principle of least privilege, allowing only authorized accesses."),
        ("NULL", "Every gap, every shortcut, every forgotten door. I will find it."),
    ]
    for i, (sp, tx) in enumerate(lines):
        d = synth_line(sp, tx, tmp / f"{i}_{sp}.wav")
        print(f"{sp:9s} {d:5.2f}s -> {tmp / f'{i}_{sp}.wav'}")
