"""v3 voice engine: Chatterbox (Resemble AI, MIT) on the RTX 4090.

Higher-quality, more natural/expressive narration than Kokoro. Each character is
a zero-shot clone of a license-clean reference clip (generated by Kokoro, Apache-2.0,
in tools/voices_ref/) so timbres are persona-matched (e.g. a YOUNGER male for Vega)
while Chatterbox supplies natural prosody + an `exaggeration` emotion knob.

Drop-in for tts2: exposes synth_line(speaker, text, out_wav) -> float and reuses
the shared pronunciation preprocessor + a light ffmpeg mastering chain. Runs in
the .venv_tts environment (chatterbox-tts + torch cu124).
"""
from __future__ import annotations
import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from tts import preprocess  # shared acronym/ID pronunciation pre-processor

import warnings
warnings.filterwarnings("ignore")

ROOT = Path(__file__).resolve().parent.parent
SR = 24000
REFDIR = ROOT / "tools" / "voices_ref"
CACHE = ROOT / "tools" / "_tmp" / "voicecache_cbx"
CACHE.mkdir(parents=True, exist_ok=True)

# character -> Chatterbox generation knobs (reference clip is voices_ref/<SPEAKER>.wav)
CAST = {
    "NARRATOR":  {"exaggeration": 0.52, "cfg_weight": 0.50, "temperature": 0.78},
    "VEGA":      {"exaggeration": 0.62, "cfg_weight": 0.46, "temperature": 0.80},
    "NOVA":      {"exaggeration": 0.70, "cfg_weight": 0.42, "temperature": 0.85},
    "ARCHIVIST": {"exaggeration": 0.38, "cfg_weight": 0.58, "temperature": 0.72},
    "NULL":      {"exaggeration": 0.82, "cfg_weight": 0.28, "temperature": 0.70},
    "HERALD":    {"exaggeration": 0.58, "cfg_weight": 0.46, "temperature": 0.80},
}

# Light, character-specific mastering (Chatterbox is already natural; just place it
# in the same -16 LUFS soundstage as music/SFX and give each voice a little space).
_NORM = "loudnorm=I=-16:TP=-1.5:LRA=11"
EFFECTS = {
    "NARRATOR":  f"highpass=f=75,acompressor=threshold=-18dB:ratio=2:attack=12:release=120,aecho=0.85:0.9:28:0.12,{_NORM}",
    "VEGA":      f"highpass=f=80,firequalizer=gain_entry='entry(3000,1.5);entry(8000,-2)',acompressor=threshold=-18dB:ratio=2:attack=12:release=120,aecho=0.85:0.9:40:0.16,{_NORM}",
    "NOVA":      f"highpass=f=95,firequalizer=gain_entry='entry(300,-1.5);entry(3500,1.5);entry(9000,-3)',acompressor=threshold=-18dB:ratio=2:attack=10:release=110,aecho=0.85:0.88:22:0.12,{_NORM}",
    "ARCHIVIST": f"highpass=f=105,firequalizer=gain_entry='entry(320,-1);entry(3200,1.5);entry(9000,-2.5)',acompressor=threshold=-18dB:ratio=2:attack=14:release=140,aecho=0.82:0.86:16:0.10,{_NORM}",
    "NULL":      f"rubberband=pitch=0.84,asubboost,highpass=f=55,firequalizer=gain_entry='entry(150,1.5);entry(1500,1);entry(3200,1.5);entry(8000,-2)',acompressor=threshold=-20dB:ratio=3:attack=8:release=160,aecho=0.9:0.9:38:0.12,lowpass=f=7200,{_NORM}",
    "HERALD":    f"highpass=f=82,firequalizer=gain_entry='entry(3000,1.5);entry(8000,-2)',acompressor=threshold=-18dB:ratio=2:attack=12:release=120,aecho=0.85:0.9:52:0.20,{_NORM}",
}

_MODEL = None
_CONDS: dict = {}


def _model():
    global _MODEL
    if _MODEL is None:
        import torch  # noqa: F401
        from chatterbox.tts import ChatterboxTTS
        dev = "cuda" if __import__("torch").cuda.is_available() else "cpu"
        _MODEL = ChatterboxTTS.from_pretrained(device=dev)
    return _MODEL


def _ref_for(speaker):
    p = REFDIR / f"{speaker}.wav"
    return p if p.exists() else (REFDIR / "NARRATOR.wav")


def _settings(speaker):
    return CAST.get(speaker, CAST["NARRATOR"])


def _synth_raw(speaker, text, raw_path):
    m = _model()
    ref = str(_ref_for(speaker))
    s = _settings(speaker)
    if speaker not in _CONDS:
        m.prepare_conditionals(ref, exaggeration=s["exaggeration"])
        _CONDS[speaker] = m.conds
    m.conds = _CONDS[speaker]
    wav = m.generate(preprocess(text), exaggeration=s["exaggeration"],
                     cfg_weight=s["cfg_weight"], temperature=s["temperature"],
                     repetition_penalty=1.2, min_p=0.05, top_p=1.0)
    import torchaudio as ta
    ta.save(str(raw_path), wav.detach().cpu(), m.sr)


def _key(speaker, text):
    ref = _ref_for(speaker)
    sig = f"cbx|{speaker}|{_settings(speaker)}|{EFFECTS.get(speaker)}|{int(ref.stat().st_mtime)}|{preprocess(text)}"
    return hashlib.md5(sig.encode("utf-8")).hexdigest()


# --- synth-time verification gate -----------------------------------------
# Chatterbox is autoregressive/stochastic: a take can drop/repeat/garble words. After
# synthesis we transcribe the clip and re-roll bad takes automatically, so a defective clip is
# never used. Tolerant of number/acronym STT readback (compares meaningful content words only).
VERIFY = __import__("os").environ.get("CC_VERIFY", "1") != "0"
VERIFY_TRIES = 4
VERIFY_THRESH = 0.8
_STOPW = set("a an the of to and or in on at is are be by we you i it that this its as for with "
             "they them then so do does did not no your our my me he she will can but if "
             "zero one two three four five six seven eight nine ten eleven twelve thirteen "
             "fourteen fifteen sixteen seventeen eighteen nineteen twenty thirty forty fifty "
             "sixty seventy eighty ninety hundred thousand".split())
_STT = None
_FAILLOG = ROOT / "tools" / "_tmp" / "synth_verify_fails.log"


def _stt():
    global _STT
    if _STT is None:
        import torch
        from faster_whisper import WhisperModel
        _STT = WhisperModel("small", device="cuda" if torch.cuda.is_available() else "cpu",
                            compute_type="float16" if torch.cuda.is_available() else "int8")
    return _STT


def _content(s):
    import re
    return [w for w in re.sub(r"[^a-z' ]", " ", s.lower()).split() if w not in _STOPW and len(w) > 2]


def _verify_score(text, wav):
    """Return (ok, recall, heard). Skips lines with <3 content words (number/acronym-only)."""
    from collections import Counter
    ew = _content(text)
    if len(ew) < 3:
        return True, 1.0, ""              # too short/number-only to verify reliably
    segs, _ = _stt().transcribe(str(wav), language="en", beam_size=5)
    heard = " ".join(x.text for x in segs).strip()
    hw = _content(heard)
    hc = Counter(hw); hit = 0
    for w in ew:
        if hc.get(w, 0) > 0:
            hit += 1; hc[w] -= 1
    recall = hit / len(ew)
    ec = Counter(ew)
    repeat = any(Counter(hw)[w] - ec.get(w, 0) >= 2 for w in set(hw))
    truncated = len(hw) < 0.4 * len(ew)
    ok = (recall >= VERIFY_THRESH) and not repeat and not truncated
    return ok, recall, heard


def _master(raw, out_wav, speaker):
    af = EFFECTS.get(speaker, EFFECTS["NARRATOR"])
    subprocess.run(["ffmpeg", "-y", "-i", str(raw), "-ar", str(SR), "-ac", "1", "-af", af, str(out_wav)],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)


def synth_line(speaker, text, out_wav) -> float:
    out_wav = Path(out_wav)
    out_wav.parent.mkdir(parents=True, exist_ok=True)
    cached = CACHE / f"{_key(speaker, text)}.wav"
    if cached.exists():
        shutil.copyfile(cached, out_wav)
    else:
        raw = out_wav.with_suffix(".raw.wav")
        best, best_recall, best_heard = None, -1.0, ""
        tries = VERIFY_TRIES if VERIFY else 1
        for attempt in range(tries):
            _synth_raw(speaker, text, raw)
            _master(raw, out_wav, speaker)
            if not VERIFY:
                break
            ok, recall, heard = _verify_score(text, out_wav)
            if recall > best_recall:
                best_recall, best_heard = recall, heard
                best = out_wav.read_bytes()
            if ok:
                best = None                # current out_wav is good
                break
        else:
            pass
        if VERIFY and best is not None:    # no attempt passed; restore best-scoring take
            out_wav.write_bytes(best)
        if VERIFY and best_recall < VERIFY_THRESH and best_recall >= 0:
            _FAILLOG.parent.mkdir(parents=True, exist_ok=True)
            with open(_FAILLOG, "a", encoding="utf-8") as fh:
                fh.write(f"{speaker} recall={best_recall:.2f} WANT[{text}] HEARD[{best_heard}]\n")
        raw.unlink(missing_ok=True)
        shutil.copyfile(out_wav, cached)
    dur = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration",
                          "-of", "csv=p=0", str(out_wav)], capture_output=True, text=True).stdout.strip()
    return float(dur)


if __name__ == "__main__":
    tmp = ROOT / "tools" / "_tmp" / "v3voices"
    lines = [
        ("NARRATOR", "Every modern organization runs on information. Protect it, and you thrive."),
        ("VEGA", "I'm Vega. Twenty guardians defend this citadel. First, AC-6, Least Privilege."),
        ("NOVA", "So that's giving people only the access they actually need? Nothing more?"),
        ("ARCHIVIST", "Employ the principle of least privilege, allowing only authorized accesses."),
        ("NULL", "Every gap, every shortcut, every forgotten door. I will find it."),
    ]
    for i, (sp, tx) in enumerate(lines):
        d = synth_line(sp, tx, tmp / f"{i}_{sp}.wav")
        print(f"{sp:9s} {d:5.2f}s -> {tmp / f'{i}_{sp}.wav'}")
